name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # or master if your default branch is 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true  # <-- this line enables cloning submodules  

      # Step 2: Setup Hugo (latest version)
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      # Step 3: Build the site (output to public/)
      - name: Build with Hugo
        run: hugo --minify

      # Step 4: Deploy public/ to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
